esphome:
  name: air2d
  friendly_name: Autotherm Air2D

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source: github://tim0816/autoterm_esphome
    components: [autoterm_uart]
    refresh: 0s

logger:
  level: DEBUG
  baud_rate: 0  # verhindert Konflikt mit UART

# Enable Home Assistant API
api:


ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_VanPi_ssid
  password: !secret wifi_VanPi_password
  domain: !secret domain

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dieselheater Hotspot"

web_server:
  port: 80

captive_portal:
  
uart:
  - id: uart_display          # Verbindung zum Bedienteil
    rx_pin: 16
    tx_pin: 17
    baud_rate: 9600
    rx_buffer_size: 1024

  - id: uart_heater           # Verbindung zur Heizung
    rx_pin: 22
    tx_pin: 23
    baud_rate: 9600
    rx_buffer_size: 1024
sensor:
  # Beispiel: Temperatur aus Home Assistant als virtuelles Paneel-Feedback
  - platform: homeassistant
    entity_id: sensor.living_area_temperature
    id: living_area_temperature
    internal: true

text_sensor:

switch:

autoterm_uart:
  uart_display_id: uart_display
  uart_heater_id: uart_heater
  internal_temp:
    name: "Internal Temperature"
  external_temp:
    name: "External Temperature"
  heater_temp:
    name: "Heater Temperature"
  voltage:
    name: "Voltage"
    accuracy_decimals: 1
  status:
    name: "Status"
  status_text:
    name: "Status Text"
  fan_speed_set:
    name: "Fan RPM Set"
    unit_of_measurement: "rpm"

  fan_speed_actual:
    name: "Fan RPM Actual"
    unit_of_measurement: "rpm"

  pump_frequency:
    name: "Pump Frequency"
    unit_of_measurement: "Hz"

  power_off:
    name: "Ausschalten"
  power_on:
    name: "Einschalten"

  fan_mode:
    name: "Lüften"


  set_temperature_control:
    name: "Solltemperatur"
  work_time_control:
    name: "Arbeitszeit"
  power_level_control:
    name: "Leistungsstufe"
  virtual_panel_temperature_control:
    name: "Virtuelle Paneeltemperatur"
    min_value: 0
    max_value: 40
    step: 1
  temperature_source_control:
    name: "Temperaturquelle"
  use_work_time_switch:
    name: "Arbeitszeit verwenden"
  wait_mode_switch:
    name: "Wartebetrieb"
  display_connected:
    name: "Display Connected"
  virtual_panel_temperature: living_area_temperature

  # --- Settings-Auswertung ---
  temperature_source:
    name: "Temperature Source"
  set_temperature:
    name: "Set Temperature"
    unit_of_measurement: "°C"
  work_time:
    name: "Work Time"
    unit_of_measurement: "min"
  power_level:
    name: "Power Level"
  wait_mode:
    name: "Wait Mode"
  use_work_time:
    name: "Use Work Time"
